### ISSUE TITLE
listchannels hygiene fails

### ISSUE THREAD

**Issue by bitromortac** [bitromortac/lndmanage#100]
```Traceback (most recent call last):
  File "./lndmanage.py", line 5, in <module>
    main()
  File "/home/boltz/testnet/lndmanage/lndmanage/lndmanage.py", line 721, in main
    parser.run_commands(node, args)
  File "/home/boltz/testnet/lndmanage/lndmanage/lndmanage.py", line 514, in run_commands
    time_interval_start=time_from, sort_string=args.sort_by)
  File "/home/boltz/testnet/lndmanage/lndmanage/lib/listings.py", line 729, in print_channels_hygiene
    time_interval_end = time.time()
NameError: name 'time' is not defined
```

The import of the time module got deleted in a previous commit.

**Comment by bitromortac** [comment]
Fixed via c82f484022d9cb235342ef75c0a3f90ca61026de.
