### ISSUE TITLE
Rebalance tries to use non-existing channel, dies

### ISSUE THREAD

**Issue by 3nprob** [bitromortac/lndmanage#114]
Running on current master:

Here, $CHANID is an open channel with almost all balance on local:

```
$ lndmanage rebalance --max-fee-sat 5 --amount 100000 $CHANID
> Loaded graph from file: n nodes, c channels.
>>> Trying to rebalance channel $CHANID with a max rate of 0.001 and a max fee of 100 sat.
>>> This is a dry run, nothing to fear.
>>> The channel status before rebalancing is lb:x sat rb:y sat cap:z sat.
>>> Trying to change the local balance by -100000 sat.
    The expected unbalancedness target is -1.01 (respecting channel reserve)
>>> Rebalancing can take some time. Please be patient!

>>> Need to still change the local balance by -100000 sat to reach the goal of -100000 sat. Fees paid up to now: 0.000 sat.
>>> Trying to rebalance with 100000 sat (attempt number 1).
    Hop 5: $CHAN2 (cap: ... sat): $ME <- $THEM
      Fees: 1.100 sat
      Liquidity penalty:  x sat
      Badness penalty:  0.000 sat
      Time penalty:  1.000 sat
   ....
    Hop 1: $CHAN (cap: ... sat): $BOB <- $ME
      Fees: 0.000 sat
      Liquidity penalty:  0.000 sat
      Badness penalty:  0.000 sat
      Time penalty:  1.000 sat
  > Route summary: amount: 100000.000 sat, total fee: x sat, fee rate: x, number of hops: 5
Traceback (most recent call last):
  File "/root/.venv/bin/lndmanage", line 8, in <module>
    sys.exit(main())
  File "/root/.venv/lib/python3.10/site-packages/lndmanage/lndmanage.py", line 617, in main
    parser.run_commands(node, args)
  File "/root/.venv/lib/python3.10/site-packages/lndmanage/lndmanage.py", line 516, in run_commands
    rebalancer.rebalance(
  File "/root/.venv/lib/python3.10/site-packages/lndmanage/lib/rebalance.py", line 624, in rebalance
    rebalance_fees_msat = self._rebalance(
  File "/root/.venv/lib/python3.10/site-packages/lndmanage/lib/rebalance.py", line 119, in _rebalance
    illiquid_channel = self.channels[illiquid_channel_id]
KeyError: $CHAN2
```

Here, `$CHAN2` is an old channel that was remotely force-closed >1y ago. lndmanage was recently started for the first time. `$CHAN2` does not appear in output from `lndmanage listchannels`.

**Comment by bitromortac** [comment]
Ok, there could be an issue with cached data. I would recommend clearing the ~/.lndmange/cache folder, but will have a look.

**Comment by 3nprob** [comment]
It's run with a fresh cache (like I mentioned: First time running lndmanage, channel was force-closed over 1 year ago).
