### ISSUE TITLE
KeyError on lndmanage.py status

### ISSUE THREAD

**Issue by lra** [bitromortac/lndmanage#19]
Trying on testnet leads to this error:
```
[analogue:~/src/lndmanage] master* ± ./lndmanage.py status    
Initializing node interface.
Initializing network graph.
Reading graph from file.
Traceback (most recent call last):
  File "./lndmanage.py", line 178, in <module>
    main()
  File "./lndmanage.py", line 129, in main
    node = LndNode()
  File "/Users/analogue/src/lndmanage/lib/node.py", line 57, in __init__
    self.set_info()
  File "/Users/analogue/src/lndmanage/lib/node.py", line 228, in set_info
    all_channels = self.get_channels(active_only=False, public_only=False)
  File "/Users/analogue/src/lndmanage/lib/node.py", line 289, in get_channels
    'alias': self.network.get_node_alias(c.remote_pubkey),
  File "/Users/analogue/src/lndmanage/lib/network.py", line 123, in get_node_alias
    return self.graph.node[node_pub_key]['alias']
  File "/Users/analogue/.pyenv/versions/3.7.1/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: '021398690de90ff0a70e29641006220c91836ff4878fb88943997ca0359c0b704c'
```

**Comment by bitromortac** [comment]
Thank you for reporting. Ok, I'm trying to cach this with d56cd075733eeba1655a578deef463ebc406ce4c, could you test this? There may be different key errors, as this node is also not known on https://1ml.com/testnet/.

**Comment by lra** [comment]
works, thanks!
