### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by jooray** [bitromortac/lndmanage#21]
```
./lndmanage.py listchannels forwardings
```

probably when I did not forward any payment yet, I get division by zero:

```
Traceback (most recent call last):
  File "./lndmanage.py", line 217, in <module>
    main()
  File "./lndmanage.py", line 174, in main
    node, sort_by=args.sort_by, time_interval_start=time_from, time_interval_end=time_to)
  File "/home/ln/lndmanage/lib/listchannels.py", line 161, in print_channels_forwardings
    channels = get_forwarding_statistics_channels(node, time_interval_start, time_interval_end)
  File "/home/ln/lndmanage/lib/forwardings.py", line 234, in get_forwarding_statistics_channels
    c['fees_total_per_week'] = channel_statistics['fees_total'] / (forwarding_analyzer.max_time_interval / 7)
ZeroDivisionError: float division by zero
```

_Thanks for great talk at #lightninghackdaymuc_

**Comment by bitromortac** [comment]
Thanks for reporting! Should be fixed by 37a29abb114a836d85372c251fe3224973cecc83.
I wish you lots of forwardings in the future! _Glad you liked it! It was fun!_
