### ISSUE TITLE
ERROR] Payment failed because the payment timed out. This is an unresolved issue.

### ISSUE THREAD

**Issue by th3geek** [bitromortac/lndmanage#29]
Running lnd 0.6.1 and Ubuntu 18.04.2 LTS and I'm having some problems. Many of the functions work good (like find new channels, list channels, etc.), but I am getting some errors every time I try to do a circle payment or a re-balance but only when the --reckless flag is enabled, otherwise the dry-run seems just fine and it appears to have RPC communication with lnd. My lnd log level is set to info and shows no traces of trying anything after performing the commands below. Any help is greatly appreciated and I'd love to send someone a 6 pack of beer over lnd if they can help me get this beast working ;)

(redacted for privacy)
When trying to circle from one channel to another:
```
user@localhost:~/lndmanage$ python3 lndmanage.py circle 111111111111111111 222222222222222222 50000 --max-fee-rate .01
Initializing node interface.
Initializing network graph.
Reading graph from file.
Next route: total fee: 2.600 sat, fee rate: 0.000052, hops: 4
   Channel hops: [111111111111111111, 111111111111111111, 222222222222222222, 222222222222222222]
This was just a dry run.
user@localhost:~/lndmanage$ python3 lndmanage.py circle 111111111111111111 222222222222222222 50000 --max-fee-rate .01 --reckless
Initializing node interface.
Initializing network graph.
Reading graph from file.
Next route: total fee: 2.600 sat, fee rate: 0.000052, hops: 4
   Channel hops: [111111111111111111, 111111111111111111, 222222222222222222, 222222222222222222]
Payment failed because the payment timed out. This is an unresolved issue.

```
Is there a way to get a more verbose debug output?

Log from circle (DEBUG level logging is set in config.ini) 
```
[2019-06-19 21:34:07 INFO] Initializing node interface.
[2019-06-19 21:34:07 INFO] Initializing network graph.
[2019-06-19 21:34:07 INFO] Reading graph from file.
[2019-06-19 21:34:08 DEBUG] External route finding:
[2019-06-19 21:34:08 DEBUG] from pubkey1
[2019-06-19 21:34:08 DEBUG]   to pubkey2
[2019-06-19 21:34:08 DEBUG] Ignored for queryroutes: channels: [], nodes: []
[2019-06-19 21:34:08 DEBUG] Channel hops:
[2019-06-19 21:34:08 DEBUG] [channelidentifier1, channelidentifier1, channelidentifier2, channelidentifier2]
[2019-06-19 21:34:08 DEBUG] Blockheight: 581548
[2019-06-19 21:34:08 DEBUG] Route construction starting.
[2019-06-19 21:34:08 DEBUG] Route from pubkey2
[2019-06-19 21:34:08 DEBUG]         to pubkey3
[2019-06-19 21:34:08 DEBUG] Policy of forwarding node: {'time_lock_delta': 40, 'fee_base_msat': 1000, 'fee_rate_milli_msat': 1, 'disabled': False}
[2019-06-19 21:34:08 DEBUG] Hop: 4
[2019-06-19 21:34:08 DEBUG]      Fees: 1050
[2019-06-19 21:34:08 DEBUG]      Fees container [0, 1050]
[2019-06-19 21:34:08 DEBUG]      Forward: 50000000
[2019-06-19 21:34:08 DEBUG] Route from pubkey3
[2019-06-19 21:34:08 DEBUG]         to pubkey2
[2019-06-19 21:34:08 DEBUG] Policy of forwarding node: {'time_lock_delta': 4, 'fee_base_msat': 0, 'fee_rate_milli_msat': 1, 'disabled': False}
[2019-06-19 21:34:08 DEBUG] Hop: 3
[2019-06-19 21:34:08 DEBUG]      Fees: 50
[2019-06-19 21:34:08 DEBUG]      Fees container [0, 1050, 50]
[2019-06-19 21:34:08 DEBUG]      Forward: 50000000
[2019-06-19 21:34:08 DEBUG] Route from pubkey1
[2019-06-19 21:34:08 DEBUG]         to pubkey3
[2019-06-19 21:34:08 DEBUG] Policy of forwarding node: {'time_lock_delta': 14, 'fee_base_msat': 1000, 'fee_rate_milli_msat': 10, 'disabled': False}
[2019-06-19 21:34:08 DEBUG] Hop: 2
[2019-06-19 21:34:08 DEBUG]      Fees: 1500
[2019-06-19 21:34:08 DEBUG]      Fees container [0, 1050, 50, 1500]
[2019-06-19 21:34:08 DEBUG]      Forward: 50001050
[2019-06-19 21:34:08 DEBUG] Route from pubkey3
[2019-06-19 21:34:08 DEBUG]         to pubkey1
[2019-06-19 21:34:08 DEBUG] Policy of forwarding node: {'time_lock_delta': 4, 'fee_base_msat': 0, 'fee_rate_milli_msat': 1, 'disabled': False}
[2019-06-19 21:34:08 DEBUG] Hop: 1
[2019-06-19 21:34:08 DEBUG]      Fees: 50
[2019-06-19 21:34:08 DEBUG]      Fees container [0, 1050, 50, 1500, 50]
[2019-06-19 21:34:08 DEBUG]      Forward: 50001100
[2019-06-19 21:34:08 INFO] Next route: total fee: 2.600 sat, fee rate: 0.000052, hops: 4
[2019-06-19 21:34:08 INFO]    Channel hops: [channelidentifier1, channelidentifier1, channelidentifier2, channelidentifier2]
[2019-06-19 21:34:08 ERROR] Payment failed because the payment timed out. This is an unresolved issue.
```

Here are the errors I'm getting while trying to re-balance :
```
user@localhost:~/lndmanage$ python3 lndmanage.py rebalance 111111111111111111 --reckless
Initializing node interface.
Initializing network graph.
Reading graph from file.
>>> Trying to rebalance channel 111111111111111111 with a max rate of 5e-05 and a max fee of 20 sat.
>>> Chunk size is set to 1.0.
>>> The channel status before rebalancing is lb:7983486 sat rb:0 sat cap:8000000 sat.
>>> Trying to change the local balance by -4016514 sat.
    The expected target is 0.00 (respecting channel reserve), requested target is 0.00.
>>> There are 5 channels with which we can rebalance (look at logs).
>>> We will try to rebalance with them one after the other.
>>> NOTE: only individual rebalance requests are optimized for fees:
    this means that there can be rebalances with less fees afterwards,
    so take a look at the dry runs first, i.e. without the --reckless flag,
    and set --max-fee-sat and --max-fee-rate accordingly.
    You may also specify a rebalancing strategy by the --strategy flag.
>>> Rebalancing can take some time. Please be patient!

-------- Rebalance from 111111111111111111 to 555555555555555555 with -4016514 sat --------
Need to still rebalance -4016514 sat to reach the goal of -4016514 sat. Fees paid up to now: 0 msat.
Next route: total fee: 22.083 sat, fee rate: 0.000005, hops: 5
   Channel hops: [111111111111111111, 111111111111111111, 636829438289051649, 636752472518623233, 555555555555555555]
   Channel is too expensive. Fee: 22083.000000 msat, requested max fee: 20.000000 msat
Too expensive.

-------- Rebalance from 111111111111111111 to 222222222222222222 with 2057864 sat --------
Need to still rebalance -4016514 sat to reach the goal of -4016514 sat. Fees paid up to now: 0 msat.
Next route: total fee: 109.067 sat, fee rate: 0.000053, hops: 4
   Channel hops: [111111111111111111, 000000000000000000, 444444444444444444, 222222222222222222]
   Channel is too expensive. Rate: 0.000053, requested max rate: 0.000050
Too expensive.

-------- Rebalance from 111111111111111111 to 888888888888888888 with 1539781 sat --------
Need to still rebalance -4016514 sat to reach the goal of -4016514 sat. Fees paid up to now: 0 msat.
Next route: total fee: 5.620 sat, fee rate: 0.000004, hops: 4
   Channel hops: [111111111111111111, 666666666666666666, 777777777777777777, 888888888888888888]
Traceback (most recent call last):
  File "/home/user/lndmanage/lib/node.py", line 196, in send_to_route
    return self._stub.SendToRouteSync(request, timeout=5*60)  # timeout after 5 minutes
  File "/home/user/.local/lib/python3.6/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/.local/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "unable to send, no routes provided"
        debug_error_string = "{"created":"@1561004132.999685080","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"unable to send, no routes provided","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/lndmanage/lib/rebalance.py", line 86, in rebalance_two_channels
    result = self.node.send_to_route(r, invoice_r_hash)
  File "/home/user/lndmanage/lib/node.py", line 198, in send_to_route
    raise PaymentTimeOut
lib.exceptions.PaymentTimeOut

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lndmanage.py", line 256, in <module>
    main()
  File "lndmanage.py", line 216, in main
    allow_unbalancing=args.allow_unbalancing, strategy=args.strategy)
  File "/home/user/lndmanage/lib/rebalance.py", line 472, in rebalance
    source_channel, target_channel, abs(amt), invoice_r_hash, self.budget_sat, dry=dry)
  File "/home/user/lndmanage/lib/rebalance.py", line 89, in rebalance_two_channels
    raise PaymentTimeOut
lib.exceptions.PaymentTimeOut
user@localhost:~/lndmanage$ 
```

**Comment by th3geek** [comment]
Also, I'm calling the script with python directly since it won't run at all otherwise (I think my default python is <3). I doubt that's the issue, but I figured I'd mention it.

**Comment by bitromortac** [comment]
Thank you for reporting this. Are you on the latest master of lndmanage? That could be an issue, because there are breaking changes in the lnd grpc. Best would be to switch to the tagged source code at https://github.com/bitromortac/lndmanage/releases/tag/v0.6.1, which is compatible with the 0.6.1 release of lnd.

As for your error, this usually happens if a node on the route is not responsive and blocks somehow the flow of the payment. I have not researched how to handle such a situation, for now I just let the payment fail after some timeout. I could catch the error and go on with trying the next route, but I'm not sure about the security implications then.

A comment on your rebalancing attempt: you try to change the balance by a relatively high amount (4 million satoshi), which might have little chances to go through the network. You could try to use smaller steps, using the `--chunksize 0.2` flag (play around with the amount). In that way your rebalancings are chopped in to smaller pieces, but you pay a bit more due to base fees.

You also have only 5 channels with which you can rebalance, which is a bit of a small number (but could work). Then it is not very good to have too many `Too expensive.` messages, which are in your case due to high total fees (> 20 sats). The default budget for the rebalance attempt is 20 sats, you can raise it with , e.g., `--max-fee-sat 50`.

_ps: thanks for the beer, but it's not necessary :)_

**Comment by th3geek** [comment]
Thank you for the fast reply. I may not have time to try this til next week. Currently my version is 0.6.1-beta commit=v0.6.1-beta-12-gf8c824fb1d6c5ef8524148f59ea5650af65af98b   is that not the correct version? 

Thanks again...

**Comment by bitromortac** [comment]
I was talking about the version of lndmanage. I tag lndmanage with the version of lnd it is compatible with. In this way, users running older lnd software can take an lndmanage version that is compatible with their lnd.

**Comment by th3geek** [comment]
I just updated to version 0.7 for both lnd and lndmanage and everything works great! Thank you so much! such an amazing utility!
