### ISSUE TITLE
Install on a RaspiBlitz: failed to install dependencies

### ISSUE THREAD

**Issue by openoms** [bitromortac/lndmanage#36]
Running on a RaspiBlitz 1.3RC2 on an Odorid HC1 with Armbian Buster
Following the install commands, ran into an error: 
```
(lndmanage) admin@HC1:~/lndmanage$ pip install -r requirements.txt
Collecting cycler==0.10.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator==4.4.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting googleapis-common-protos==1.5.9 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/76/a6/903a1c1c1fd676660174a9be4ec777c9b547392f640b16a326182b8fe484/googleapis-common-protos-1.5.9.tar.gz
Collecting grpcio==1.19.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/e3/aa/6ee1f1c0b35d270725abff07f8d807c0413154af14cd019fd3aa3ab69d64/grpcio-1.19.0.tar.gz (14.6MB)
     |████████████████████████████████| 14.6MB 5.4MB/s 
Collecting grpcio-tools==1.13.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/25/aa/70ff3d76f4b659ff2e067ed778b4e90a35239e859ac993cb3ffb3b3f955c/grpcio-tools-1.13.0.tar.gz (1.9MB)
     |████████████████████████████████| 1.9MB 15.6MB/s 
Collecting kiwisolver==1.0.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/31/60/494fcce70d60a598c32ee00e71542e52e27c978e5f8219fae0d4ac6e2864/kiwisolver-1.0.1.tar.gz
Collecting matplotlib==3.0.3 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/26/04/8b381d5b166508cc258632b225adbafec49bbe69aa9a4fa1f1b461428313/matplotlib-3.0.3.tar.gz (36.6MB)
     |████████████████████████████████| 36.6MB 67kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/admin/.venvs/lndmanage/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a_f8ffue/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a_f8ffue/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-a_f8ffue/matplotlib/
    Complete output (50 lines):
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC
                            8.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Try installing freetype with `apt-get install
                            * libfreetype6-dev` and pkg-config with `apt-get
                            * install pkg-config`
                            * Try installing png with `apt-get install
                            * libpng12-dev` and pkg-config with `apt-get install
                            * pkg-config`
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
```
$ python --version`
Python 3.7.3

python-dev is already the newest version (2.7.16-1).
```
Solved with: 
```
sudo apt install pkg-config
sudo apt-get install libfreetype6-dev
sudo apt-get remove python-dev
sudo apt-get install python3-dev
```
After which `pip install -r requirements.txt` ran successfully.

The config.ini has been filled as follows:
```
# network settings
[network]
lnd_grpc_host = 127.0.0.1:10009
# tls and admin macaroon can be found in .lnd folder
tls_cert_file = /home/admin/.lnd/tls.cert
admin_macaroon_file = /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon

[logging]
loglevel = INFO
```

Working without further issues so far.
Will continue testing on a RPi4 as well.

**Comment by bitromortac** [comment]
Perfect, thanks for updating/reporting!

**Comment by openoms** [comment]
Testing on RPi4 with the latest RaspiBlitz 1.3RC5. The installation went without errors, but getting the error when running the first time:

```
(lndmanage) admin@RPi4:~/lndmanage $ ./lndmanage.py status
Traceback (most recent call last):
  File "/home/admin/.venvs/lndmanage/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/admin/.venvs/lndmanage/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/admin/.venvs/lndmanage/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lndmanage.py", line 6, in <module>
    from lib.listchannels import ListChannels
  File "/home/admin/lndmanage/lib/listchannels.py", line 10, in <module>
    from lib.forwardings import get_forwarding_statistics_channels
  File "/home/admin/lndmanage/lib/forwardings.py", line 4, in <module>
    import numpy as np
  File "/home/admin/.venvs/lndmanage/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/admin/.venvs/lndmanage/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/admin/.venvs/lndmanage/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

All dependencies were met on installation and reinstalling numpy with pip did not make a difference.
Any ideas?

**Comment by bitromortac** [comment]
Could you try:
https://github.com/Kitt-AI/snowboy/issues/262 ?

**Comment by openoms** [comment]
great it seems running:
`sudo apt-get install libatlas-base-dev`
solved the problem. 

Now the script starts, the error is I presume because this test node has 0 channels: 
```
(lndmanage) admin@RPi4:~ $ lndmanage/lndmanage.py status
Initializing node interface.
Initializing network graph.
Saved graph is too old. Fetching new one.
Traceback (most recent call last):
  File "lndmanage/lndmanage.py", line 361, in <module>
    main()
  File "lndmanage/lndmanage.py", line 274, in main
    node = LndNode()
  File "/home/admin/lndmanage/lib/node.py", line 59, in __init__
    self.set_info()
  File "/home/admin/lndmanage/lib/node.py", line 229, in set_info
    all_channels = self.get_open_channels(active_only=False, public_only=False)
  File "/home/admin/lndmanage/lib/node.py", line 252, in get_open_channels
    channels_data = raw_channels.ListFields()[0][1]
IndexError: list index out of range
```

I really enjoy using your script on my main node with 20 channels. I find it`s output very informative too.
Will keep recommending it!

Would like to see some kind of automation. 
Could be either a daemon function (with preset rebalance triggers) or an automated service running periodically. What do you think?

**Comment by openoms** [comment]
Getting problems on the RaspBlitz again:
`(venv) admin@HC2:~$ python3 -m pip install lndmanage`
```
Collecting lndmanage
  Using cached https://files.pythonhosted.org/packages/1d/9c/7776a829b14dc6c56d241e48334cf3b26fecee717271cb90772760f6ccce/lndmanage-0.7.1.1-py3-none-any.whl
Collecting protobuf==3.7.1 (from lndmanage)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f5/e4/7c86c9c9b4bad7632e107064fb07d0812b9858a49830d0b2477081bf1267/protobuf-3.7.1-py2.py3-none-any.whl (404kB)
    100% |████████████████████████████████| 409kB 891kB/s 
Collecting decorator==4.4.0 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: wheel in ./venv/lib/python3.7/site-packages (from lndmanage) (0.33.6)
Collecting googleapis-common-protos==1.5.9 (from lndmanage)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/76/a6/903a1c1c1fd676660174a9be4ec777c9b547392f640b16a326182b8fe484/googleapis-common-protos-1.5.9.tar.gz
Requirement already satisfied: cycler==0.10.0 in ./venv/lib/python3.7/site-packages (from lndmanage) (0.10.0)
Collecting pyparsing==2.4.0 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil==2.8.0 in ./venv/lib/python3.7/site-packages (from lndmanage) (2.8.0)
Collecting grpcio-tools==1.13.0 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/25/aa/70ff3d76f4b659ff2e067ed778b4e90a35239e859ac993cb3ffb3b3f955c/grpcio-tools-1.13.0.tar.gz
Collecting numpy==1.16.2 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/cf/8d/6345b4f32b37945fedc1e027e83970005fc9c699068d2f566b82826515f2/numpy-1.16.2.zip
Collecting grpcio==1.19.0 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/e3/aa/6ee1f1c0b35d270725abff07f8d807c0413154af14cd019fd3aa3ab69d64/grpcio-1.19.0.tar.gz
Collecting matplotlib==3.0.3 (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/26/04/8b381d5b166508cc258632b225adbafec49bbe69aa9a4fa1f1b461428313/matplotlib-3.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC
                            8.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.17.2]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Try installing freetype with `apt-get install
                            * libfreetype6-dev` and pkg-config with `apt-get
                            * install pkg-config`
                            * Try installing png with `apt-get install
                            * libpng12-dev` and pkg-config with `apt-get install
                            * pkg-config`
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-10prmyi1/matplotlib/
```

Tried to add matplotlib separately, but is fails too https://pastebin.com/raw/G4TS9cBW

I have got these installed: 
```
sudo apt-get install python3-dev libevent-dev pkg-config
pip3 install wheel
```

**Comment by bitromortac** [comment]
Ok, I think having matplotlib in the requirements is too heavy. I removed it, but might add it again in the future.
Could you try the new pypi package lndmanage 0.7.1.2?

**Comment by openoms** [comment]
Thanks it worked now. 
Must note that it might need a couple of retries, but eventually installs everything.

**Comment by openoms** [comment]
New dependency requirement:
Error after pip install when running lndmanage:
```
Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```
Solved with installing: 
`sudo apt-get install libatlas-base-dev`
