### ISSUE TITLE
listchannels --help in interactive mode prints stack trace 

### ISSUE THREAD

**Issue by sangaman** [bitromortac/lndmanage#56]
I see an error stack trace when I call `listchannels --help` from interactive mode, in addition to the normal help output:

```
$ lndmanage listchannels --help
usage: lndmanage.py listchannels [-h]
                                 {rebalance,inactive,forwardings,hygiene} ...

positional arguments:
  {rebalance,inactive,forwardings,hygiene}
    rebalance           displays unbalanced channels
    inactive            displays inactive channels
    forwardings         displays channels with forwarding information
    hygiene             displays channels with information for channel closing

optional arguments:
  -h, --help            show this help message and exit
Exception encountered.
Traceback (most recent call last):
  File "/home/bitcoin/lndmanage/lib/python3.6/site-packages/lndmanage/lndmanage.py", line 445, in main
    args = parser.parser.parse_args(args_list)
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1963, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1940, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1146, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1034, in __call__
    parser.exit()
  File "/usr/lib/python3.6/argparse.py", line 2389, in exit
    _sys.exit(status)
SystemExit: 0
```

**Comment by frennkie** [comment]
The same is true for an empty input.

I would suggest to catch `argparse.ArgumentError: argument cmd`, additionally check for `-h` and `--help` and for `empty` default to help. Any other entry (e.g. typo in `listchannel`) could also print a more user friendly error message (instead of stack trace).

**Comment by bitromortac** [comment]
Thanks for reporting and the PR!

Concerning the incorrect input of commands, one idea to solve this would be to make suggestions based on the most similar command and maybe also autocompletion on input.
