### ISSUE TITLE
error during setup

### ISSUE THREAD

**Issue by rookey** [bitromortac/lndmanage#62]
During first time installation, I received the following errors, lndmanage could not be created:

admin@MyNode:~ $ python3 -m venv venv
admin@MyNode:~ $ source venv/bin/activate
(venv) admin@MyNode:~ $ python3 -m pip install lndmanage
Collecting lndmanage
  Downloading https://files.pythonhosted.org/packages/ab/f5/380fd312aa078a99b3e1c2bc7e955a8531f47db1bc387acc9a73d4e0629a/lndmanage-0.9.0-py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 214kB/s
Collecting googleapis-common-protos==1.5.9 (from lndmanage)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://www.piwheels.org/simple/googleapis-common-protos/googleapis_common_protos-1.5.9-py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 25kB/s
Collecting decorator==4.4.0 (from lndmanage)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting grpcio-tools==1.13.0 (from lndmanage)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/90/d8/603fdf0fca7dcfe3b6b91fe1b6a94e65bd69bf1372d102a9ac190a71b889/grpcio_tools-1.13.0-cp35-cp35m-linux_armv7l.whl (19.8MB)
    100% |████████████████████████████████| 19.8MB 13kB/s
Collecting wheel (from lndmanage)
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting numpy==1.16.2 (from lndmanage)
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.16.2-cp35-cp35m-linux_armv7l.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 31kB/s
Collecting pyparsing==2.4.0 (from lndmanage)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 664kB/s
Collecting python-dateutil==2.8.0 (from lndmanage)
Exception:
Traceback (most recent call last):
  File "/home/admin/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/admin/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/admin/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/venv/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/admin/venv/lib/python3.5/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/admin/venv/lib/python3.5/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/admin/venv/lib/python3.5/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/admin/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/admin/venv/lib/python3.5/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/admin/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/admin/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/admin/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/admin/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/admin/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/admin/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
(venv) admin@MyNode:~ $ lndmanage status
-bash: lndmanage: command not found

**Comment by bitromortac** [comment]
It seems you are running mynodebtc. I don't really have experience with it, but lndmanage should be preinstalled already (see https://github.com/mynodebtc/mynode/blob/master/setup/setup_device.sh). Could you check it is available?
Also, what does `python3 --version` say?

**Comment by rookey** [comment]
Sorry, I forgot to mention - I'm running it on a RaspiBlitz image ( https://github.com/rootzoll/raspiblitz/ ), and I'm on Python 3.5.3 here. Thanks!

**Comment by bitromortac** [comment]
Hm OK, could be a python issue. I'm developing on Python3.6 and that is the minimal requirement.

Maybe you're able to upgrade to python 3.6 via your package management software. If that doesn't work you could try something like https://unix.stackexchange.com/questions/332641/how-to-install-python-3-6#332658.

**Comment by rookey** [comment]
Thanks for your feedback … based on your suggestion I've installed python 3.6, but am getting this error message now:

(venv) admin@ThisLNDNode:~/Python-3.6.9 $ lndmanage
Traceback (most recent call last):
  File "/home/admin/Python-3.6.9/venv/bin/lndmanage", line 7, in <module>
    from lndmanage.lndmanage import main
  File "/home/admin/Python-3.6.9/venv/lib/python3.6/site-packages/lndmanage/lndmanage.py", line 7, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by bitromortac** [comment]
That's strange, because the readline module should be part of the standard library and this shouldn't happen if you really are in fact running the pyhton3.6 executable.
I would stay out of your Python-3.6.9 folder, when installing the virtual environment. Maybe try
```
$ cd /home/admin/
$ ./path/to/python3.6 -m venv venv
$ source venv/bin/activate
$ (venv) pip install lndmanage
```

**Comment by bitromortac** [comment]
Closing due to inactivity.
